version: "3.8"

services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME:-localstack-smartpotsystem}"
    image: localstack/localstack
    ports:
      - "4566:4566"            # Porta principale per AWS mockato
      - "4510-4559:4510-4559"  # Range per altri servizi AWS
    environment:
      - DEBUG=${DEBUG:-0}
      - SERVICES=iam,s3,sqs,lambda,dynamodb,kinesis,events,apigateway,logs  # Servizi LocalStack
      - LOCALSTACK_HOST=localhost
      - GATEWAY_LISTEN=0.0.0.0:4566
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
    env_file:
      - .env
    networks:
      - smartpotsystem-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4566/_localstack/health"]
      interval: 30s
      timeout: 20s
      retries: 5

  mosquitto:
    container_name: "mosquitto-broker"
    image: eclipse-mosquitto
    ports:
      - "1883:1883"  # Porta MQTT
      - "9001:9001"  # Porta WebSocket (opzionale)
    volumes:
      - "./mosquitto/config:/mosquitto/config"  # Configurazione Mosquitto
      - "./mosquitto/data:/mosquitto/data"      # Dati persistenti Mosquitto
      - "./mosquitto/log:/mosquitto/log"        # Log Mosquitto
    networks:
      - smartpotsystem-network
    restart: always

networks:
  smartpotsystem-network:
    driver: bridge

